### ISSUE TITLE
Cesium website bug: no other languages are available

### ISSUE THREAD

**Issue by calbasi** [Monnaies-Libres/cesium_website#8]
Hi, I've opened a thread at the Duniter forum with this stuff:

https://forum.duniter.org/t/cesium-website-bug-no-other-languages-are-available/9242

Crossposting:

The language selector is not running. And this URL is not resolving:

cesium(dot)app(slash)es

I’m using Firefox and Chromium, on linux.

**Comment by BorisPAING** [comment]
Hi @calbasi , 

Here is the right place to post this.

Thank you for pointing that out. I'll investigate this right now.

**Comment by poka-IT** [comment]
Hi @calbasi ,

This should be ok now.

**Comment by calbasi** [comment]
Thanks a lot!
